services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lt-planner-postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lt-db
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data

